# Generated by Django 3.0.1 on 2020-01-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/imagess/no-img.jpg', upload_to='media/imagess/'),
        ),
    ]
