# Generated by Django 3.0.1 on 2020-01-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/images/name.jpg', upload_to='media/images/'),
        ),
    ]
