# Generated by Django 3.0.1 on 2020-01-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/name.jpg', upload_to='images/'),
        ),
    ]
