# Generated by Django 3.0.1 on 2020-01-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
