# Generated by Django 3.0.1 on 2020-01-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
