# Generated by Django 3.0.1 on 2020-02-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jahr', models.DateTimeField()),
                ('Landkreis', models.CharField(max_length=40)),
                ('BIPEinwohner', models.IntegerField()),
                ('BIPErwerb', models.IntegerField()),
            ],
        ),
    ]
