# Generated by Django 3.0.1 on 2020-02-06 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_innodata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Einwohner', models.IntegerField()),
                ('Erwerbstaetiger', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BWS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Einwohner', models.IntegerField()),
                ('Erwerbstaetiger', models.IntegerField()),
                ('ErwerbstaetigerLandForstFischerei', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Oekonomie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jahr', models.IntegerField()),
                ('Landkreis', models.CharField(max_length=40)),
                ('BIPField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BIP')),
                ('BWSField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BWS')),
            ],
        ),
    ]
