# Generated by Django 3.0.1 on 2020-03-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20200207_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='author',
        ),
        migrations.DeleteModel(
            name='InnoData',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='bws',
            name='Einwohner',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bws',
            name='Erwerbstaetiger',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bws',
            name='ErwerbstaetigerLandForstFischerei',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
