# Generated by Django 3.0.1 on 2020-03-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20200320_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='bip',
            name='EinwohnerUNIT',
            field=models.CharField(default='EUR', max_length=130),
        ),
    ]
